### ISSUE TITLE
Some entities not updating

### ISSUE THREAD

**Issue by JoseMadbird** [jhansche/ha-teslafi#65]
Hello,

since yesterday i have issues with some entities in HA TeslaFI. I´ve removed the integration and configure again and problem still happening.

In the Teslafi.com i can see fine, but in the integration is not working some entities . I have an error "not possible to configure".

![Image](https://github.com/user-attachments/assets/a7149393-f03f-4395-9abe-d8c86cc2b35d)

![Image](https://github.com/user-attachments/assets/b80de017-da36-44b3-abf0-256706a8c101)

Some entities are updating and some others no. Sorry for spanish in the picture. (Desconocido means unknow)

Could you please help?

Many thanks in advance.

**Comment by jcjones** [comment]
Can you look in the Home Assistant Log for an error from TeslaFi and let us know what it is? Probably this is like my issue with charger amperage, which I have a PR to fix in #62.

![Image](https://github.com/user-attachments/assets/f119c5fd-de9f-49ea-aa6c-ff032d6ce0b0)

**Comment by onrust** [comment]
Same issue here, this is my log:

```
Logger: homeassistant.config_entries
Bron: config_entries.py:637
Eerst voorgekomen: 1 maart 2025 om 18:33:47 (2 gebeurtenissen)
Laatst gelogd: 1 maart 2025 om 18:42:29

Error setting up entry Black Betty for teslafi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 637, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/teslafi/__init__.py", line 62, in async_setup_entry
    coordinator.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 178, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/teslafi/number.py", line 63, in _handle_coordinator_update
    return super()._handle_coordinator_update()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 559, in _handle_coordinator_update
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1081, in __async_calculate_state
    capability_attr = self.capability_attributes
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 254, in capability_attributes
    ATTR_STEP: self._calculate_step(min_value, max_value),
               ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 337, in _calculate_step
    value_range = abs(max_value - min_value)
                      ~~~~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```


And:

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant
Bron: custom_components/teslafi/util.py:14
integratie: TeslaFi (documentatie, problemen)
Eerst voorgekomen: 1 maart 2025 om 19:09:33 (1 gebeurtenissen)
Laatst gelogd: 1 maart 2025 om 19:09:33

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 479, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 178, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/teslafi/number.py", line 54, in _handle_coordinator_update
    self._attr_native_value = self._get_value()
                              ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/teslafi/base.py", line 87, in _get_value
    upstream = self.entity_description.value(self.coordinator.data, self.hass)
  File "/config/custom_components/teslafi/number.py", line 37, in <lambda>
    if (x := v.get("charge_current_request", v.charger_current))
                                             ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/teslafi/model.py", line 206, in charger_current
    value = _int_or_none(self.get("charger_actual_current"))
  File "/config/custom_components/teslafi/util.py", line 14, in _int_or_none
    return None if src is None else int(src)
                                    ~~~^^^^^
ValueError: invalid literal for int() with base 10: '2.00000002'
```

**Comment by hvdrie** [comment]
Same issue here. Integration failed to set up, several entities have no values at all or incorrect values (e.g. charger voltage = 2,00 , charger current = 0 and charge time remaining = 1,00.

**Comment by JoseMadbird** [comment]
> Can you look in the Home Assistant Log for an error from TeslaFi and let us know what it is? Probably this is like my issue with charger amperage, which I have a PR to fix in [#62](https://github.com/jhansche/ha-teslafi/issues/62).
> 
> ![Image](https://github.com/user-attachments/assets/f119c5fd-de9f-49ea-aa6c-ff032d6ce0b0)

![Image](https://github.com/user-attachments/assets/c5ae5c7b-24f1-4fe5-8a87-2f0dc04176ae)

This is the message i´m receiving when reload the integration:

![Image](https://github.com/user-attachments/assets/8c2ae299-3bae-422e-8ceb-e1721cacebf4)

Thanks in advance

**Comment by JoseMadbird** [comment]
> Today I removed and then reinstalled this integration. At first, all seemed to be working again, but after a few minutes the same error returned.

Same here.....

**Comment by hvdrie** [comment]
> Today I removed and then reinstalled this integration. At first, all seemed to be working again, but after a few minutes the same error returned.


Same here. I removed it completely, then installed the latest version (2.10.1). For a few minutes everything seemed to work fine. For instance: the battery percentage was displayed correctly. But a few minutes later the battery percentage changed to "unknown". The same happened to several other entities. None of them are updating anymore after a few minutes.

**Comment by ulricdabe** [comment]
Hi, 
Same here, 2 cars, one fails, the other not 

![Image](https://github.com/user-attachments/assets/252ad7d4-61e8-4b7b-9aca-c8dd13731039)

**Comment by JoseMadbird** [comment]
> Hi, Same here, 2 cars, one fails, the other not
> 
> ![Image](https://github.com/user-attachments/assets/252ad7d4-61e8-4b7b-9aca-c8dd13731039)

now only receiving this error when i´m enabling "

![Image](https://github.com/user-attachments/assets/6276a400-ab2c-494a-b078-417bbad0e0d5)

"

**Comment by hvdrie** [comment]
When I disable the "request_charger_current" I can indeed reload the integration and it doesn't fail. However being able to dynamically change the charger current depending on my solar panels production is the whole purpose of the automation that I am using.

Besides, the only entity on my dashboard that has a value now is the battery percentage. Several other entities, including switch.xxx_charging and sensor.xxx_charging_current are still either unknown or 0. Ar those showing for anyone else?

I have upgraded to version 2.10.1, not sure whether that makes a difference.

**Comment by jcjones** [comment]
https://github.com/jhansche/ha-teslafi/pull/64 fixes the `request_charger_current` issue, it just needs to be merged and released.

**Comment by JoseMadbird** [comment]
> [#64](https://github.com/jhansche/ha-teslafi/pull/64) fixes the `request_charger_current` issue, it just needs to be merged and released.

Just checked and working fine!!!!! Many thanks

**Comment by JoseMadbird** [comment]
> When I disable the "request_charger_current" I can indeed reload the integration and it doesn't fail. However being able to dynamically change the charger current depending on my solar panels production is the whole purpose of the automation that I am using.
> 
> Besides, the only entity on my dashboard that has a value now is the battery percentage. Several other entities, including switch.xxx_charging and sensor.xxx_charging_current are still either unknown or 0. Ar those showing for anyone else?
> 
> I have upgraded to version 2.10.1, not sure whether that makes a difference.

With the solution by jcjones is working when "request_charger_current" is enable

Nevertheless, this one:

![Image](https://github.com/user-attachments/assets/7a96f12b-1712-47c3-a86f-f2f11b024d87)
has to keep disable, otherwise some other entities fail

**Comment by LampyDave** [comment]
> Nevertheless, this one:
> 'Charger Apparent Power'
> has to keep disable, otherwise some other entities fail

Thank you for that tip - disabled that one and my tyre pressures have come back :)

**Comment by jcjones** [comment]
> has to keep disable, otherwise some other entities fail

That'll be affected by https://github.com/jhansche/ha-teslafi/pull/63, my other PR. However, I am [still having issues with that one myself](https://github.com/jhansche/ha-teslafi/pull/63#issuecomment-2701545504) and need to iterate on it some more

**Comment by JoseMadbird** [comment]
> > has to keep disable, otherwise some other entities fail
> 
> That'll be affected by [#63](https://github.com/jhansche/ha-teslafi/pull/63), my other PR. However, I am [still having issues with that one myself](https://github.com/jhansche/ha-teslafi/pull/63#issuecomment-2701545504) and need to iterate on it some morI have again _

> > has to keep disable, otherwise some other entities fail
> 
> That'll be affected by [#63](https://github.com/jhansche/ha-teslafi/pull/63), my other PR. However, I am [still having issues with that one myself](https://github.com/jhansche/ha-teslafi/pull/63#issuecomment-2701545504) and need to iterate on it some more

I have again the same issue.....

**Comment by onrust** [comment]
> I have again the same issue.....

Same here, it's been working with ups and downs.

**Comment by jhansche** [comment]
I believe TeslaFi is applying some changes that the integration can't deal with, combined with potentially HA imposing stricter expectations for certain entities. And there are a few different, unrelated issues noted here. 

* Unable to convert a decimal value to an int - resolved in v2.11 by converting to float first 
* Dividing by 0 volts - resolved in v2.11 by requiring a non-0 value for voltage 
* Bad max for charge current slider - appears to be a TeslaFi bug; mitigated in v2.11 by taking the current value as max. May also be a HA update contributing to this

**Comment by hvdrie** [comment]
Thank you @jhansche for creating this new version. I hope that it will solve my issues with dynamically adjusting the charging speed.

How can I install this version in HACS? When I try to install I am getting v2.10.1 as the latest version.

**Comment by JoseMadbird** [comment]
Hello, 

still not working.....

![Image](https://github.com/user-attachments/assets/5219b490-0fa1-4d64-8df2-789615d18ab6)

**Comment by JoseMadbird** [comment]
now i can´t see tyres pressure and temperature (cabin & outside)

**Comment by hvdrie** [comment]
@JoseMadbird how did you manage to install version 2.11? When I try I keep getting version 2.10.1.

**Comment by JoseMadbird** [comment]
> [@JoseMadbird](https://github.com/JoseMadbird) how did you manage to install version 2.11? When I try I keep getting version 2.10.1.

Hello, copying all this files into teslafi custom components folder

![Image](https://github.com/user-attachments/assets/27a51731-5a80-4d65-90d6-2d6c28821e3f)

**Comment by hvdrie** [comment]
Thanks @JoseMadbird. Unfortunately I am not able to manually copy files into the folder at the moment, until I have resolved some other challenges. So I guess that I have to wait for an official release then :-(

**Comment by JoseMadbird** [comment]
> Thanks [@JoseMadbird](https://github.com/JoseMadbird). Unfortunately I am not able to manually copy files into the folder at the moment, until I have resolved some other challenges. So I guess that I have to wait for an official release then :-(

Are you unable to access to your HA in this way?

![Image](https://github.com/user-attachments/assets/05abb137-6f69-41b4-9992-8dbac092859e)

then you get:

![Image](https://github.com/user-attachments/assets/df4901eb-71ec-42fe-9d35-4d8c7d83b533)

After do this, remove the car, and add again the API, now EVERYTHING is running again, thanks @jhansche

**Comment by jhansche** [comment]
@hvdrie please see hacs documentation: 
* https://www.hacs.xyz/docs/use/entities/switch/
* or install it manually by running the service: https://www.hacs.xyz/docs/use/entities/update/

**Comment by hvdrie** [comment]
> [@hvdrie](https://github.com/hvdrie) please see hacs documentation:
> 
> * https://www.hacs.xyz/docs/use/entities/switch/
> * or install it manually by running the service: https://www.hacs.xyz/docs/use/entities/update/

Thank you very much, @jhansche, that was very helpful. I enabled the switch and was able to download the 2.11 pre-release. 
The car is not at home ate the moment, so I wont be able to test everything until tonight, but at least I am not getting any error message and I can permanently see the battery charge level, wich previously disappeared a few seconds after (re)installing the integration.

I know that it is challenging to keep everything up and running while both Tesla and TeslaFi are constantly making changes to the APIs and I appreciate the work that you are doing.

**Comment by jhansche** [comment]
I don't, but I appreciate the gesture 🙂

**Comment by hvdrie** [comment]
@jhansche I can confirm that everything is working perfectly fine again for me. Charging speed, battery%, remaining charge time, charge current and most importantly request charge current. All available and stable. I second the idea of a Buymeacoffee or similar. In any case, thanks again for getting this to work again.
